// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int32
	Name              pgtype.Text
	PhoneNumber       string
	Otp               pgtype.Text
	OtpExpirationTime pgtype.Timestamp
}
