// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, phone_number)
VALUES ($1, $2)
RETURNING id, name, phone_number, otp, otp_expiration_time
`

type CreateUserParams struct {
	Name        pgtype.Text
	PhoneNumber string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Otp,
		&i.OtpExpirationTime,
	)
	return i, err
}

const generateOTP = `-- name: GenerateOTP :one
UPDATE users
SET otp = $1, otp_expiration_time = $2
WHERE phone_number = $3
RETURNING id, name, phone_number, otp, otp_expiration_time
`

type GenerateOTPParams struct {
	Otp               pgtype.Text
	OtpExpirationTime pgtype.Timestamp
	PhoneNumber       string
}

func (q *Queries) GenerateOTP(ctx context.Context, arg GenerateOTPParams) (User, error) {
	row := q.db.QueryRow(ctx, generateOTP, arg.Otp, arg.OtpExpirationTime, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Otp,
		&i.OtpExpirationTime,
	)
	return i, err
}

const verifyOTP = `-- name: VerifyOTP :one
SELECT id, name, phone_number, otp, otp_expiration_time
FROM users
WHERE phone_number = $1
`

func (q *Queries) VerifyOTP(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, verifyOTP, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Otp,
		&i.OtpExpirationTime,
	)
	return i, err
}
